name: Root Folder Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # 금고(Secrets)에 등록된 이름과 똑같이 _TRAVEL을 붙였습니다.
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KOSVI_TRAVEL }}
          channelId: live
          projectId: kosvi-travel